// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ValueObjectInheritanceTestConsoleApp.Infra.Db.Contexts;

#nullable disable

namespace ValueObjectInheritanceTestConsoleApp.Migrations
{
    [DbContext(typeof(TestDbContext))]
    partial class TestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OwnershipTestConsoleApp.Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_customer");

                    b.ToTable("customer", (string)null);
                });

            modelBuilder.Entity("OwnershipTestConsoleApp.Domain.Customer", b =>
                {
                    b.OwnsOne("ValueObjectInheritanceTestConsoleApp.Domain.DocumentContainer", "_documentContainer", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime?>("_issueDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("document_issue_date");

                            b1.Property<string>("_serialNumber")
                                .HasColumnType("text")
                                .HasColumnName("document_serial_number");

                            b1.Property<int>("_type")
                                .HasColumnType("integer")
                                .HasColumnName("document_type");

                            b1.HasKey("CustomerId");

                            b1.ToTable("customer");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId")
                                .HasConstraintName("fk_customer_customer_id");
                        });

                    b.Navigation("_documentContainer");
                });
#pragma warning restore 612, 618
        }
    }
}
